name: CI

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GH_OAUTH }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Replace toc-versions
        uses: NumyAddon/ToCVersions@v1

#      - name: Create Retail Package
#        uses: BigWigsMods/packager@v2
